### ISSUE TITLE
Issue templeteを共通のものを使用できるようにする

### ISSUE THREAD

**Issue by Galliver7** [artery-app/Barulhento#11]
共通のissue templeteを使用したいので、以下のレポジトリにsub moduleを適用する

- core
- frontend
- module-chat-mail
- module-x (将来的に)

適用するtempleteは

- Barulhento

から拾ってくる

**Comment by rikusen0335** [comment]
経過報告兼メモとしてとして残しておきます:
ISSUE_TEMPLATEフォルダをサブモジュールとして読み込ませたいので、テストとして[ISSUE_TEMPLATE用のリポジトリ](https://github.com/artery-app/issue-templates)を作って読み込ませたが、サブモジュールは入っているように見えても、Issue Templateの方は適用されていないようだった。また、[frontendのリポジトリ](https://github.com/artery-app/frontend)からIssue Template用の設定ボタンが消えていたので、なんらかおかしいよう。

**Comment by rikusen0335** [comment]
実際、New Issueを押すと、以前のようにIssue Templateを選ぶ画面ではなく、そのままIssueを書く画面まで遷移してしまっていた。

**Comment by qwexvf** [comment]
メモ用
https://github.community/t/issue-template-for-organization-does-not-work/2049

**Comment by qwexvf** [comment]
現在こちらの対応中で今日中に全部のリポジトリに適用させます！

**Comment by qwexvf** [comment]
https://github.com/artery-app/frontend/pull/30

一旦ここでテンプレートの内容がOKか確認もらえたら他のリポジトリにPR出します。

**Comment by rikusen0335** [comment]
とりあえず、正常動作が確認できたのでクローズします。
