### ISSUE TITLE
Readmeにそれぞれのアクションの仕様の説明を追加する

### ISSUE THREAD

**Issue by Galliver7** [artery-app/Barulhento#13]
@qwexvf の方で整理するのでついでにReadmeで整理をしてしまいましょう！

_Originally posted by @Galliver7 in https://github.com/artery-app/Barulhento/issues/2#issuecomment-698891494_

**Comment by rikusen0335** [comment]
https://github.com/artery-app/Barulhento/commit/884c8d2fa3b841798eff7fee743348285163c72c
とりあえず、このコミットでガイドを書きました。ちょっと最後の方集中力が途切れそうだったので文章として変になってるかもしれませんので、不備があったときには言っていただければ修正いたします。コミットへのリファレンスは忘れていました...

**Comment by Galliver7** [comment]
ドキュメント確認できたので、クローズします。
