### ISSUE TITLE
フロントエンドのプルリクエストを視覚的に確認できるようにする

### ISSUE THREAD

**Issue by Galliver7** [artery-app/Barulhento#4]
@rikusen0335 さんのAWESOMEな開発プロセスの理解による[プルリクエスト](https://github.com/artery-app/frontend/pull/14)が来ておりますが、拙者のお粗末なdevスキルではその成果物を確認することに至りませぬ。

stagingに自動的に deployされるなど、なんらかの視覚的な確認でできるようになっていればご幸甚に仕る
デザインツールのURLをリンクするだけでもOK

![screenshot_525](https://user-images.githubusercontent.com/8030470/89122619-93d43e80-d503-11ea-960b-d8470f4cf19e.png)

↑ 完全に理解したGalliverの図

**Comment by rikusen0335** [comment]
あーすいません、了解です。それでは、developとか作ってみます
![gomennasai_tatakanaide](https://user-images.githubusercontent.com/19174234/89122710-98e5bd80-d504-11ea-852e-8c803b8fda3d.jpg)

**Comment by Galliver7** [comment]
あ、その方法でできるんですね！
よろしくおねがいします！

**Comment by Galliver7** [comment]
![cool](https://user-images.githubusercontent.com/8030470/89122867-f6c6d500-d505-11ea-8807-d8895963acbe.gif)

さいこう。

**Comment by rikusen0335** [comment]
こっちもクローズしておきます！
アクセスは https://web.develop.artery.chat まで

**Comment by rikusen0335** [comment]
すいません、どなたかクローズお願いします！権限ありませんでした...
